/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controleos;

import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mest2
 */
public class ConsultaCliente extends javax.swing.JFrame {

    /**
     * Creates new form PesquisaCliente
     */
    public ConsultaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblConsultaCliente = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        lblCpf4 = new javax.swing.JLabel();
        txtAddreesCli4 = new javax.swing.JTextField();
        lblAddress4 = new javax.swing.JLabel();
        lblZipCode4 = new javax.swing.JLabel();
        lblDateOfBirth4 = new javax.swing.JLabel();
        txtCodCli4 = new javax.swing.JTextField();
        txtNomeCli4 = new javax.swing.JTextField();
        txtCpfCli4 = new javax.swing.JTextField();
        lblCod4 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        FtxtDateOfBirdCli4 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCityCli4 = new javax.swing.JTextField();
        ftxtCepCli4 = new javax.swing.JFormattedTextField();
        lblNumberCli4 = new javax.swing.JLabel();
        txtNumberCli4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ftxtPhone4 = new javax.swing.JFormattedTextField();
        ftxtCelPhone4 = new javax.swing.JFormattedTextField();
        btnSearch = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Clientes");
        setIconImage(new ImageIcon(getClass().getResource("imagens/icone.png")).
            getImage());
        setMaximumSize(new java.awt.Dimension(923, 452));
        setMinimumSize(new java.awt.Dimension(923, 452));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblConsultaCliente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblConsultaCliente.setText("Consulta de Clientes");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCpf4.setText("CPF:");

        txtAddreesCli4.setEditable(false);

        lblAddress4.setText("Endereço:");

        lblZipCode4.setText("CEP:");

        lblDateOfBirth4.setText("Data de nascimento:");

        lblCod4.setText("Código:");

        lblName4.setText("Nome:");

        FtxtDateOfBirdCli4.setEditable(false);
        try {
            FtxtDateOfBirdCli4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setText("Cidade:");

        txtCityCli4.setEditable(false);

        ftxtCepCli4.setEditable(false);
        try {
            ftxtCepCli4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblNumberCli4.setText("Número:");

        txtNumberCli4.setEditable(false);

        jLabel15.setText("Telefone:");

        jLabel16.setText("Celular:");

        ftxtPhone4.setEditable(false);
        try {
            ftxtPhone4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtPhone4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftxtPhone4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtPhone4ActionPerformed(evt);
            }
        });

        ftxtCelPhone4.setEditable(false);
        try {
            ftxtCelPhone4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCelPhone4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCod4)
                    .addComponent(lblName4)
                    .addComponent(lblCpf4)
                    .addComponent(lblDateOfBirth4)
                    .addComponent(lblAddress4)
                    .addComponent(jLabel14)
                    .addComponent(lblNumberCli4))
                .addGap(18, 57, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddreesCli4)
                    .addComponent(FtxtDateOfBirdCli4)
                    .addComponent(txtCpfCli4)
                    .addComponent(txtNomeCli4)
                    .addComponent(txtCodCli4)
                    .addComponent(txtCityCli4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(txtNumberCli4, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblZipCode4)
                        .addGap(35, 35, 35)
                        .addComponent(ftxtCepCli4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(170, 170, 170)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ftxtPhone4)
                    .addComponent(ftxtCelPhone4, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel15)
                                                    .addComponent(ftxtPhone4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblCod4)
                                                        .addComponent(txtCodCli4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtNomeCli4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel16)
                                                        .addComponent(ftxtCelPhone4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCpfCli4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCpf4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FtxtDateOfBirdCli4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDateOfBirth4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddreesCli4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAddress4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCityCli4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ftxtCepCli4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblZipCode4)
                        .addComponent(lblNumberCli4)
                        .addComponent(txtNumberCli4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnChange.setText("Alterar");
        btnChange.setEnabled(false);
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnDelete.setText("Deletar");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConsultaCliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblConsultaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)
                    .addComponent(btnSearch)
                    .addComponent(btnChange)
                    .addComponent(btnDelete))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void ftxtPhone4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtPhone4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtPhone4ActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
       txtCodCli4.setEditable(false);
       txtNomeCli4.setEditable(true);
       txtCpfCli4.setEditable(true);
       FtxtDateOfBirdCli4.setEditable(true);
       txtAddreesCli4.setEditable(true);
       txtCityCli4.setEditable(true);
       txtNumberCli4.setEditable(true);
       ftxtCepCli4.setEditable(true);
       ftxtPhone4.setEditable(true);
       ftxtCelPhone4.setEditable(true);
       
       btnSalvar.setEnabled(true);
       btnDelete.setEnabled(true);
       
        
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String pesquisa = "", 
               parametro = "",
               cpf = txtCpfCli4.getText(),
               nome = txtNomeCli4.getText(),
               dados[][] = null,
               selecaoDeUsuario="",
               strJOption=""; 
                             
        if(!txtCodCli4.getText().equals("")){
            pesquisa = " = " + txtCodCli4.getText();
            parametro = "id";
        }else{
            if(!txtNomeCli4.getText().equals("")){
                pesquisa = " LIKE " + "'%"+ txtNomeCli4.getText() + "%'";
                parametro = "nome";
            }else{
                if(!cpf.equals("") || cpf.length() == 12){
                    pesquisa = " = " + cpf;
                    parametro = "cpf";
                }
            }
        }
        
        if(pesquisa.equals("")) 
            JOptionPane.showMessageDialog(null, "Insira um valor para pesquisa!", "Campos em branco", JOptionPane.ERROR_MESSAGE);
        else{
            dados = new ConnectDB().searchClient( parametro, pesquisa);
            if(Integer.parseInt(dados[0][49]) >= 1){
                strJOption = "Selecione um cliente apartir do id: \n";
              for(int x =1; x <= Integer.parseInt(dados[0][49]); x++){
                  strJOption += x + "   " + dados[2][x-1] + "     " + dados[3][x-1] + "\n";
              }
              selecaoDeUsuario = JOptionPane.showInputDialog(strJOption);
            }else{
              selecaoDeUsuario = dados[0][49];
            }   
        }
        int parametroGravacao=Integer.parseInt(selecaoDeUsuario)-1;
        
        if(!"".equals(selecaoDeUsuario)){
            txtCodCli4.setText(dados[1][parametroGravacao]);
            txtNomeCli4.setText(dados[2][parametroGravacao]);
            txtCpfCli4.setText(dados[3][parametroGravacao]);
            FtxtDateOfBirdCli4.setText(new SubstituirCaracteres().apenasNumeros(dados[4][parametroGravacao]));
            txtAddreesCli4.setText(dados[5][parametroGravacao]);
            txtCityCli4.setText(dados[6][parametroGravacao]);
            txtNumberCli4.setText(dados[7][parametroGravacao]);
            ftxtCepCli4.setText(new SubstituirCaracteres().apenasNumeros(dados[8][parametroGravacao]));
            ftxtPhone4.setText(dados[9][parametroGravacao]);
            ftxtCelPhone4.setText(dados[10][parametroGravacao]);
            
            btnChange.setEnabled(true);
           
        }
        
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        boolean campos=true;
        String[] dadosCliente = new String[10]; 
        
        dadosCliente[0]=txtNomeCli4.getText();
        dadosCliente[1]=txtCpfCli4.getText();
        dadosCliente[2]=new SubstituirCaracteres().tiraData(FtxtDateOfBirdCli4.getText());
        dadosCliente[3]=txtAddreesCli4.getText();
        dadosCliente[4]=txtCityCli4.getText();
        dadosCliente[5]=txtNumberCli4.getText();
        dadosCliente[6]=new SubstituirCaracteres().retiraCep(ftxtCepCli4.getText());
        dadosCliente[7]=ftxtPhone4.getText();
        dadosCliente[8]=ftxtCelPhone4.getText();
        dadosCliente[9]=txtCodCli4.getText();
        
        if (dadosCliente[0].equals("")) {
           JOptionPane.showMessageDialog(null, "Insira um nome! \n Campo nome em branco!", "Nome", JOptionPane.ERROR_MESSAGE);
           campos = false;
        }else{
            try {
                long testaCpf = Long.parseLong(dadosCliente[1]);
                } catch (Exception e) {
                    System.out.println(e);
                  JOptionPane.showMessageDialog(null, "Insira apenas números!", "CPF", JOptionPane.ERROR_MESSAGE);
                  campos = false;
                }
                  if (dadosCliente[1].equals("")) {
                    JOptionPane.showMessageDialog(null, "Insira um CPF!", "CPF", JOptionPane.ERROR_MESSAGE);
                    campos = false;
                }else
            if (dadosCliente[2].equals("    -  -  ")) {
            JOptionPane.showMessageDialog(null, "Insira uma data de nascimento!", "Data", JOptionPane.ERROR_MESSAGE);
            campos = false;
        }else
            if (dadosCliente[3].equals("")) {
            JOptionPane.showMessageDialog(null, "Insira um endereço!", "Endereço", JOptionPane.ERROR_MESSAGE);
            campos = false;
        }else
            if (dadosCliente[4].equals("")) {
            JOptionPane.showMessageDialog(null, "Insira uma cidade!", "Cidade", JOptionPane.ERROR_MESSAGE);
            campos = false;
        }else{
                try {
                   long testaNum = Long.parseLong(dadosCliente[5]);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Insira apenas números!", "Número da casa", JOptionPane.ERROR_MESSAGE);
                    campos = false;
                }
                if (dadosCliente[5].equals("")) {
                JOptionPane.showMessageDialog(null, "Insira um número!", "Número da casa", JOptionPane.ERROR_MESSAGE);
                campos = false;
            }else{
                    String testaif = new SubstituirCaracteres().apenasNumeros(dadosCliente[6]);
                try {
                   long testaCep = Long.parseLong(testaif);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Insira apenas números!", "Cep", JOptionPane.ERROR_MESSAGE);
                    campos = false;
                }
                if (testaif.equals("")) {
                JOptionPane.showMessageDialog(null, "Insira um Cep!", "Cep", JOptionPane.ERROR_MESSAGE);
                campos = false;
                }else{
                    try {
                       long testaFone = Long.parseLong(new SubstituirCaracteres().apenasNumeros(dadosCliente[7]));
                     } catch (Exception e) {
                         JOptionPane.showMessageDialog(null, "Insira apenas números!", "Telefone", JOptionPane.ERROR_MESSAGE);
                         campos = false;
                     }
                     if (new SubstituirCaracteres().apenasNumeros(dadosCliente[7]).equals("")) {
                     JOptionPane.showMessageDialog(null, "Insira um Telefone!", "Telefone", JOptionPane.ERROR_MESSAGE);
                     campos = false;
                     }else{
                        try {
                            long testaCell = Long.parseLong(new SubstituirCaracteres().apenasNumeros(dadosCliente[8]));
                         } catch (Exception e) {
                             JOptionPane.showMessageDialog(null, "Insira apenas números!", "Celular", JOptionPane.ERROR_MESSAGE);
                             campos = false;
                         }
                         if (new SubstituirCaracteres().apenasNumeros(dadosCliente[8]).equals("")) {
                         JOptionPane.showMessageDialog(null, "Insira um Celular!", "Celular", JOptionPane.ERROR_MESSAGE);
                         campos = false;
                         }    
                      }    
                }
        
            }
        }        } 
 
        
        if (campos) {
            new ConnectDB().alterarCliente(dadosCliente);
            txtCodCli4.setText("");
            txtNomeCli4.setText("");
            txtCpfCli4.setText("");
            FtxtDateOfBirdCli4.setText("");
            txtAddreesCli4.setText("");
            txtCityCli4.setText("");
            txtNumberCli4.setText("");
            ftxtCepCli4.setText("");
            ftxtPhone4.setText("");
            ftxtCelPhone4.setText("");
            
            
       txtCodCli4.setEditable(true);
       txtNomeCli4.setEditable(true);
       txtCpfCli4.setEditable(true);
       FtxtDateOfBirdCli4.setEditable(false);
       txtAddreesCli4.setEditable(false);
       txtCityCli4.setEditable(false);
       txtNumberCli4.setEditable(false);
       ftxtCepCli4.setEditable(false);
       ftxtPhone4.setEditable(false);
       ftxtCelPhone4.setEditable(false);
       
       btnSalvar.setEnabled(false);
       btnDelete.setEnabled(false);
       btnChange.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String id=txtCodCli4.getText();
        
        
        Component nulo = null;
        int resposta = JOptionPane.showConfirmDialog (nulo, "Deseja continuar?" , "Confirmar Logoff" ,
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (resposta == JOptionPane.NO_OPTION) {
            System.out.println ( "Botão não clicado" );
            } else  if (resposta == JOptionPane.YES_OPTION) {
                new ConnectDB().deleteClient(id);
                
                txtCodCli4.setText("");
                txtNomeCli4.setText("");
                txtCpfCli4.setText("");
                FtxtDateOfBirdCli4.setText("");
                txtAddreesCli4.setText("");
                txtCityCli4.setText("");
                txtNumberCli4.setText("");
                ftxtCepCli4.setText("");
                ftxtPhone4.setText("");
                ftxtCelPhone4.setText("");
            
            
                txtCodCli4.setEditable(true);
                txtNomeCli4.setEditable(false);
                txtCpfCli4.setEditable(false);
                FtxtDateOfBirdCli4.setEditable(false);
                txtAddreesCli4.setEditable(false);
                txtCityCli4.setEditable(false);
                txtNumberCli4.setEditable(false);
                ftxtCepCli4.setEditable(false);
                ftxtPhone4.setEditable(false);
                ftxtCelPhone4.setEditable(false);

                btnSalvar.setEnabled(false);
                btnDelete.setEnabled(false);
                btnChange.setEnabled(false);
            System.out.println ( "Botão Sim clicado" );
            } else  if (resposta == JOptionPane.CLOSED_OPTION) {
            System.out.println ( "JOptionPane fechado" );
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCliente().setVisible(true);
            }
        });
    }
    
    public static void main(String args[]) {
        init();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtxtDateOfBirdCli4;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JFormattedTextField ftxtCelPhone4;
    private javax.swing.JFormattedTextField ftxtCepCli4;
    private javax.swing.JFormattedTextField ftxtPhone4;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAddress4;
    private javax.swing.JLabel lblCod4;
    private javax.swing.JLabel lblConsultaCliente;
    private javax.swing.JLabel lblCpf4;
    private javax.swing.JLabel lblDateOfBirth4;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblNumberCli4;
    private javax.swing.JLabel lblZipCode4;
    private javax.swing.JTextField txtAddreesCli4;
    private javax.swing.JTextField txtCityCli4;
    private javax.swing.JTextField txtCodCli4;
    private javax.swing.JTextField txtCpfCli4;
    private javax.swing.JTextField txtNomeCli4;
    private javax.swing.JTextField txtNumberCli4;
    // End of variables declaration//GEN-END:variables
}
