/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controleos;

import controleos.Usuario.Usuario;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import static org.eclipse.persistence.jpa.jpql.utility.CollectionTools.array;

/**
 *
 * @author mest2
 */
public class GerenciamentoDeUsuarios extends javax.swing.JFrame {
    
    /**
     * Creates new form GerenciamentoDeUsuarios
     */
    public GerenciamentoDeUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("controleos?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        loginKeyQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT l FROM LoginKey l");
        loginKeyList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : loginKeyQuery.getResultList();
        btnNewUser = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnDelete = new javax.swing.JButton();
        lblGeneciaUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCod = new javax.swing.JLabel();
        lblNameUser = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        lblPasswordConfirm = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNameUser = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtNewPassword = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JTextField();
        btnSearchUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Usuários");

        btnNewUser.setText("Novo Usuário");
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar Usuário");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Salvar");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Deletar Usuário");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblGeneciaUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGeneciaUser.setText("Gerenciamento de Usuários");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCod.setText("Código:");

        lblNameUser.setText("Nome do usuário:");

        lblLogin.setText("Login:");

        lblPassword.setText("Senha:");

        lblNewPassword.setText("Nova Senha:");

        lblPasswordConfirm.setText("Confirme a Senha:");

        txtCod.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCod.setText("0");

        txtNameUser.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtLogin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        txtPassword.setEditable(false);
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtNewPassword.setEditable(false);
        txtNewPassword.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtConfirmPassword.setEditable(false);
        txtConfirmPassword.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCod)
                    .addComponent(lblNameUser)
                    .addComponent(lblLogin)
                    .addComponent(lblPassword)
                    .addComponent(lblNewPassword)
                    .addComponent(lblPasswordConfirm))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCod, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtNameUser)
                    .addComponent(txtLogin)
                    .addComponent(txtPassword)
                    .addComponent(txtNewPassword)
                    .addComponent(txtConfirmPassword))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameUser)
                    .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPassword)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordConfirm)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        btnSearchUser.setText("Buscar Usuário");
        btnSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnNewUser)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchUser)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblGeneciaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGeneciaUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnEdit)
                    .addComponent(btnNewUser)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnSearchUser))
                .addGap(25, 25, 25))
        );

        getAccessibleContext().setAccessibleDescription("Gerenciamento de Usuários");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUserActionPerformed
        txtCod.setEditable(true);
        txtLogin.setEditable(true);
        txtNameUser.setEditable(true);
        txtPassword.setEditable(false);
        txtConfirmPassword.setEditable(false);
        txtNewPassword.setEditable(false);
      
        int id = Integer.parseInt(txtCod.getText());
        String nome = txtNameUser.getText();
        String login = txtLogin.getText();
        
        UsuarioDAO userDAO = new UsuarioDAO();
        
        try {
            String[][] array = userDAO.pesquisar(id, nome, login);
            
            
            int lines = array.length;
            
            if (lines > 0) {
                String listaUser = "cogigo   nome    login\n"; 
                while (lines > 0 ) {
                    if(array[lines-1][0] != null){
                        listaUser += lines + "               ";
                        listaUser += array[lines-1][2] + "   ";
                        listaUser += array[lines-1][1];
                        listaUser += "\n";
                    }
                    
                    lines--;
                }
                int escolhido =  Integer.parseInt(JOptionPane.showInputDialog(null, listaUser))-1;
                
                txtCod.setText(array[escolhido][0]);
                txtLogin.setText(array[escolhido][1]);
                txtNameUser.setText(array[escolhido][2]);
                /*String ocultaSenha = array[escolhido][3];
                for(int x=0;x < ocultaSenha.length();x++  ){
                    
                }*/
                txtPassword.setText("*****");
                
                
                btnEdit.setEnabled(true);
                btnDelete.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "Não ha dados compativeis!");
            }
                
            
            
        } catch (SQLException ex) {
            Logger.getLogger(GerenciamentoDeUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchUserActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        txtNameUser.setEditable(true);
        txtLogin.setEditable(true);
        txtPassword.setEditable(true);
        txtConfirmPassword.setEditable(true);
        txtNewPassword.setEditable(false);
        txtCod.setEditable(false);
        
        //Limpa campos
                txtCod.setText("0");
                txtConfirmPassword.setText(null);
                txtLogin.setText(null);
                txtNameUser.setText(null);
                txtNewPassword.setText(null);
                txtPassword.setText(null);
        
        btnSave.setEnabled(true);
        
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        //Edição de Usuario
        
        txtCod.setEditable(false);
        txtNameUser.setEditable(true);
        txtLogin.setEditable(true);
        txtPassword.setEditable(false);
        txtNewPassword.setEditable(true);
        txtConfirmPassword.setEditable(true);
        
        btnSave.setEnabled(true);
        btnNewUser.setEnabled(false);
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Usuario user = new Usuario();
        JDialog.setDefaultLookAndFeelDecorated (true);
        Component nulo = null;
        int resposta = JOptionPane.showConfirmDialog (nulo, "Deseja mesmo excluir o usuario? \n " +txtNameUser.getText() , "Confirmar exclusão" ,
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (resposta == JOptionPane.YES_OPTION) {
            user.setId(Integer.parseInt(txtCod.getText()));
            new UsuarioDAO().delete(user);
            
           txtCod.setText("0");
           txtConfirmPassword.setText(null);
           txtLogin.setText(null);
           txtNameUser.setText(null);
           txtNewPassword.setText(null);
           txtPassword.setText(null);
        }
        
        
        
        
        
        
        
        
   
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String senha = txtPassword.getText();
        String CSenha = txtConfirmPassword.getText();
        String NSenha = txtNewPassword.getText();
        int id = Integer.parseInt(txtCod.getText());
        String nome = txtNameUser.getText();
        String login = txtLogin.getText();
        
        
        
        Usuario usuario = new Usuario();
        if (0 == id ) {
            
            usuario.setId(0);
            usuario.setLogin(login);
            usuario.setNome(nome);
                if(senha.equals(CSenha)){
                    usuario.setSenha(senha);
                    if (id == 0) {
                    UsuarioDAO usuarioDao = new UsuarioDAO();
                    try {
                        usuarioDao.gravar(nome, login, senha);
                        JOptionPane.showMessageDialog(null, "Salvo com sucesso!");

                        //Limpa campos
                        txtCod.setText("0");
                        txtConfirmPassword.setText(null);
                        txtLogin.setText(null);
                        txtNameUser.setText(null);
                        txtNewPassword.setText(null);
                        txtPassword.setText(null);
                    } catch (SQLException e) {
                         JOptionPane.showMessageDialog(null, "Erro ao salvar os dados!");
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "As senhas não são iguais!");
                }

                
        }else{
             usuario.setId(Integer.parseInt(txtCod.getText()));
             System.out.println(usuario.getId());
             usuario.setLogin(login);
             usuario.setNome(nome);
             if(NSenha.equals(CSenha) && !NSenha.equals(null)){
                 senha = NSenha;
             }else{
                 senha = null;
             }
                 
             usuario.setSenha(senha);
             UsuarioDAO userDAO =new UsuarioDAO();
             userDAO.altera(usuario);
             
        }
        
       
       
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void init() {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoDeUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }  catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoDeUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoDeUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(GerenciamentoDeUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                 new GerenciamentoDeUsuarios().setVisible(true);
            }
        });
       
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchUser;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblGeneciaUser;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConfirm;
    private java.util.List<controleos.LoginKey> loginKeyList;
    private javax.persistence.Query loginKeyQuery;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtConfirmPassword;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
